services:
  koreader:
    image: ghcr.io/zephyros-dev/koreader:latest
    build:
      context: . # Remove this line if you only use the image from the registry
      # target: fedora # Use this build stage if you use fedora-derivate distro
    ports:
      - "5673-5674:5673-5674"
     volumes:
       - /docker/koreader/config:/config # Persistent storage
    # # For hardware acceleration, check out the base image documentations:
    # # https://github.com/linuxserver/docker-baseimage-selkies?tab=readme-ov-file#dri3-gpu-acceleration
    # devices:
    #   - /dev/dri:/dev/dri
    # deploy:
    #   resources:
    #     reservations:
    #       devices:
    #         - driver: nvidia
    #           count: 1
    #           capabilities: [gpu]
    cap_add:
      - CAP_NET_RAW # Required for some network options like calibre
