services:
  koreader:
    image: ghcr.io/zephyros-dev/koreader:latest
    build: . # Remove this line if you only use the image from the registry
    ports:
      - "3000:3000"
    volumes:
      - ./volume/config:/config # Persistent storage
    cap_add:
      - CAP_NET_RAW # Required for some network options like calibre
