name: Build
on:
  push:
    branches:
      - main
    paths:
      - Dockerfile
      - .github/workflows/build.yaml
env:
  REGISTRY: ghcr.io
  IMAGE_NAME: zephyros-dev/koreader
jobs:
  build-and-push-image:
    # https://stackoverflow.com/questions/70377390/is-there-any-way-to-trigger-a-specific-github-action-workflow-by-commit-message
    if: "!contains(github.event.head_commit.message, 'curl')" # Do not run if it only updates the curl version
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5
      - name: Set up QEMU
        uses: docker/setup-qemu-action@29109295f81e9208d7d86ff1c6c12d2833863392 # v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@e468171a9de216ec08956ac3ada2f0791b6bd435 # v3
      - name: Log in to the Container registry
        uses: docker/login-action@5e57cd118135c172c3672efd75eb46360885c0ef
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Get Koreader version
        id: koreader_version
        run: echo "version=$(cat Dockerfile | grep -oP '(?<=ARG KOREADER_VERSION=).+(?=)')" >> $GITHUB_OUTPUT
      - name: Get fedora version
        id: fedora_version
        run: echo "version=$(cat Dockerfile | grep -oP '(?<=fedora).+(?=@)')" >> $GITHUB_OUTPUT
      - name: Extract metadata (tags, labels) for Docker fedora
        id: meta_fedora
        uses: docker/metadata-action@032a4b3bda1b716928481836ac5bfe36e1feaad6
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            # set latest tag for default branch
            type=raw,value=${{ steps.koreader_version.outputs.version }}-fedora{{ steps.fedora_version.outputs.version }}
      - name: Build and push Docker image fedora
        uses: docker/build-push-action@9e436ba9f2d7bcd1d038c8e55d039d37896ddc5d
        with:
          context: .
          push: true
          platforms: linux/amd64, linux/arm64
          target: fedora
          tags: ${{ steps.meta_fedora.outputs.tags }}
          labels: ${{ steps.meta_fedora.outputs.labels }}
      - name: Get debian version
        id: debian_version
        run: echo "version=$(cat Dockerfile | grep -oP '(?<=debian).+(?=@)')" >> $GITHUB_OUTPUT
      - name: Extract metadata (tags, labels) for Docker
        id: meta_debian
        uses: docker/metadata-action@032a4b3bda1b716928481836ac5bfe36e1feaad6
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            # set latest tag for default branch
            type=raw,value=latest,enable={{ is_default_branch }}
            type=raw,value=${{ steps.koreader_version.outputs.version }}
            type=raw,value=${{ steps.koreader_version.outputs.version }}-debian{{ steps.debian_version.outputs.version }}
      - name: Build and push Docker image debian
        uses: docker/build-push-action@9e436ba9f2d7bcd1d038c8e55d039d37896ddc5d
        with:
          context: .
          push: true
          platforms: linux/amd64, linux/arm64
          tags: ${{ steps.meta_debian.outputs.tags }}
          labels: ${{ steps.meta_debian.outputs.labels }}
