name: Test image build
on:
  push:
    branches-ignore:
      - main
    paths:
      - Dockerfile
jobs:
  test-build-image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
      - name: Set up QEMU
        uses: docker/setup-qemu-action@49b3bc8e6bdd4a60e6116a5414239cba5943d3cf # v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@c47758b77c9736f4b2ef4073d4d51994fabfe349 # v3
      - name: Build docker image
        uses: docker/build-push-action@8796455d3250bab0b8ea17630e10645c29a1249a
        with:
          context: .
          push: false
          platforms: linux/amd64, linux/arm64
