name: Test image build
on:
  push:
    branches:
      - "!main"
    paths:
      - Dockerfile
jobs:
  test-build-image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4
      - name: Set up QEMU
        uses: docker/setup-qemu-action@49b3bc8e6bdd4a60e6116a5414239cba5943d3cf # v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@988b5a0280414f521da01fcc63a27aeeb4b104db # v3
      - name: Build and push Docker image
        uses: docker/build-push-action@32945a339266b759abcbdc89316275140b0fc960
        with:
          context: .
          push: false
          platforms: linux/amd64, linux/arm64
